import streamlit as st

st.header("🔍 Key Insights & Intelligence Summary")

st.markdown("""
### **1. Adversaries are using consistent C2 infrastructure across global regions**
Analysis of `filtered_iocs_threatfox` shows repeated use of:
- **Ports 443, 995, 80, 2078, 2222**
- **IP:Port combinations tied to QakBot, Emotet, and Feodo**
- **C2 servers hosted in AS37705 (TOPNET), AS8151 (UNINET), AS11830, AS1241, WIND-AS**

**Implication:**  
Attackers prefer encrypted channels (HTTPS/443) and legacy mail ports (995) to blend into normal traffic.  
This increases detection difficulty for financial institutions relying on traditional firewall rules.

---

### **2. Significant ransomware activity targeting financial sector (Akira group)**
The `finance_group_iocs` dataset contains:
- **Dozens of Akira ransomware hashes (MD5, SHA256)**
- **Multiple Bitcoin ransom payment addresses**
- **MITRE ATT&CK TTPs including:**  
  - Credential Access (T1003.001)  
  - Lateral Movement (T1021.001)  
  - Remote Execution (T1047)  
  - Defense Evasion (T1112, T1562.001)  
  - Data Encryption for Impact (T1486)

**Implication:**  
Akira is actively developing and deploying new builds.  
Financial organizations must prioritize:
- Credential hardening  
- Lateral movement monitoring  
- Backup integrity validation  
- Ransomware tabletop exercises

---

### **3. Surge in banking-themed phishing campaigns**
The `verified_online_banking_finance` dataset shows:
- **30+ active phishing URLs**
- Hosted on **Vercel, Lovely.app, dweb.link, .co.nl**, and other low-cost hosting
- All tagged as **banking phishing**
- Many mimic login portals:  
  - `secure-bank-login-verify.com`  
  - `ww-bank-authenticate.net`  
  - `credit-pichincha-flow.lovable.app`

**Implication:**  
Attackers are abusing modern cloud hosting platforms to quickly deploy and rotate phishing sites.  
Financial institutions must strengthen:
- Brand monitoring  
- Customer phishing education  
- URL filtering and takedown processes

---

### **4. QakBot remains a persistent threat to financial networks**
Cross‑referencing `filtered_iocs_threatfox` and `verified_online_banking_finance` reveals:
- **Multiple QakBot C2 servers** active in Feb–Mar 2026  
- IPs such as `102.158.228.15:443`, `197.0.81.220:443`, `41.62.43.21:443`

**Implication:**  
QakBot continues to be used as an initial access vector for ransomware groups.  
Financial institutions should prioritize:
- Blocking known QakBot C2 infrastructure  
- Monitoring suspicious outbound 443 traffic  
- Detecting DLL injection and persistence mechanisms

---

### **5. Ramnit botnet domains indicate automated credential theft**
The dataset includes **100+ autogenerated Ramnit C2 domains**, such as:
- `wnlgghgffr.com`
- `wpaxdlstrs.com`
- `xoodachpaujnikmpp.com`

**Implication:**  
Ramnit is still active and using domain‑generation algorithms (DGAs).  
Financial login portals are high‑value targets for Ramnit credential theft modules.

---
""")
