import streamlit as st
import pandas as pd
import plotly.express as px
from pyvis.network import Network
import streamlit.components.v1 as components

st.set_page_config(page_title="Threat Intelligence Dashboard", layout="wide")

# ---------------------------------------------------------
# INTELLIGENCE SUMMARY SECTION (ADDED)
# ---------------------------------------------------------
st.header("🔍 Key Insights & Intelligence Summary")

st.markdown("""
### **1. Adversaries are using consistent C2 infrastructure across global regions**
Analysis of `filtered_iocs_threatfox` shows repeated use of:
- **Ports 443, 995, 80, 2078, 2222**
- **IP:Port combinations tied to QakBot, Emotet, and Feodo**
- **C2 servers hosted in AS37705 (TOPNET), AS8151 (UNINET), AS11830, AS1241, WIND-AS**

**Implication:**  
Attackers prefer encrypted channels (HTTPS/443) and legacy mail ports (995) to blend into normal traffic.  
This increases detection difficulty for financial institutions relying on traditional firewall rules.

---

### **2. Significant ransomware activity targeting financial sector (Akira group)**
The `finance_group_iocs` dataset contains:
- **Dozens of Akira ransomware hashes (MD5, SHA256)**
- **Multiple Bitcoin ransom payment addresses**
- **MITRE ATT&CK TTPs including:**  
  - Credential Access (T1003.001)  
  - Lateral Movement (T1021.001)  
  - Remote Execution (T1047)  
  - Defense Evasion (T1112, T1562.001)  
  - Data Encryption for Impact (T1486)

**Implication:**  
Akira is actively developing and deploying new builds.  
Financial organizations must prioritize:
- Credential hardening  
- Lateral movement monitoring  
- Backup integrity validation  
- Ransomware tabletop exercises

---

### **3. Surge in banking-themed phishing campaigns**
The `verified_online_banking_finance` dataset shows:
- **30+ active phishing URLs**
- Hosted on **Vercel, Lovely.app, dweb.link, .co.nl**, and other low-cost hosting
- All tagged as **banking phishing**
- Many mimic login portals:  
  - `secure-bank-login-verify.com`  
  - `ww-bank-authenticate.net`  
  - `credit-pichincha-flow.lovable.app`

**Implication:**  
Attackers are abusing modern cloud hosting platforms to quickly deploy and rotate phishing sites.  
Financial institutions must strengthen:
- Brand monitoring  
- Customer phishing education  
- URL filtering and takedown processes

---

### **4. QakBot remains a persistent threat to financial networks**
Cross‑referencing `filtered_iocs_threatfox` and `verified_online_banking_finance` reveals:
- **Multiple QakBot C2 servers** active in Feb–Mar 2026  
- IPs such as `102.158.228.15:443`, `197.0.81.220:443`, `41.62.43.21:443`

**Implication:**  
QakBot continues to be used as an initial access vector for ransomware groups.  
Financial institutions should prioritize:
- Blocking known QakBot C2 infrastructure  
- Monitoring suspicious outbound 443 traffic  
- Detecting DLL injection and persistence mechanisms

---

### **5. Ramnit botnet domains indicate automated credential theft**
The dataset includes **100+ autogenerated Ramnit C2 domains**, such as:
- `wnlgghgffr.com`
- `wpaxdlstrs.com`
- `xoodachpaujnikmpp.com`

**Implication:**  
Ramnit is still active and using domain‑generation algorithms (DGAs).  
Financial login portals are high‑value targets for Ramnit credential theft modules.

---
""")

# ---------------------------------------------------------
# LOAD DATASETS SAFELY FROM data/ FOLDER
# ---------------------------------------------------------
processed_ports = pd.read_csv("data/processed_port_iocs.csv", on_bad_lines="skip")
threat_events = pd.read_csv("data/threat_events.csv", on_bad_lines="skip")

# ---------------------------------------------------------
# DROPDOWN MENU
# ---------------------------------------------------------
viz = st.selectbox(
    "Select a visualization:",
    [
        "C2 Port Network Visualization",
        "Akira Ransomware – MITRE Technique Frequency"
    ]
)

# ---------------------------------------------------------
# 1. C2 PORT NETWORK VISUALIZATION (PyVis)
# ---------------------------------------------------------
if viz == "C2 Port Network Visualization":
    st.subheader("🕸️ C2 Port Network Visualization (Port Frequency Network)")

    if "port" not in processed_ports.columns:
        st.error("❌ processed_port_iocs.csv must contain a 'port' column.")
    else:
        processed_ports["port"] = pd.to_numeric(processed_ports["port"], errors="coerce")

        port_counts = (
            processed_ports["port"]
            .value_counts()
            .reset_index()
        )
        port_counts.columns = ["Port", "Count"]

        net = Network(height="600px", width="100%", bgcolor="#ffffff", font_color="black")

        net.add_node("C2 Ports", size=50, color="#ff4d4d")

        for _, row in port_counts.iterrows():
            port = str(row["Port"])
            count = int(row["Count"])

            net.add_node(
                port,
                size=10 + count,
                title=f"Port {port} — Count: {count}",
                color="#1f77b4"
            )

            net.add_edge("C2 Ports", port)

        net.save_graph("port_network.html")

        HtmlFile = open("port_network.html", "r", encoding="utf-8")
        components.html(HtmlFile.read(), height=600)

# ---------------------------------------------------------
# 2. AKIRA RANSOMWARE – MITRE TECHNIQUE BAR CHART
# ---------------------------------------------------------
elif viz == "Akira Ransomware – MITRE Technique Frequency":
    st.subheader("🔥 Akira Ransomware – MITRE Technique Frequency")

    threat_events = threat_events.rename(columns={
        "technique": "mitre_technique",
        "ttp": "mitre_technique",
        "attack_id": "mitre_technique"
    })

    if "mitre_technique" not in threat_events.columns:
        st.error("❌ threat_events.csv must contain a 'mitre_technique' column.")
    else:
        ttp_counts = (
            threat_events["mitre_technique"]
            .value_counts()
            .reset_index()
        )
        ttp_counts.columns = ["MITRE Technique", "Count"]

        fig = px.bar(
            ttp_counts,
            x="MITRE Technique",
            y="Count",
            title="Akira Ransomware – MITRE Technique Usage",
            color="Count",
            color_continuous_scale="Reds"
        )

        fig.update_layout(xaxis_title="MITRE Technique", yaxis_title="Frequency")

        st.plotly_chart(fig, use_container_width=True)
